/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    pages: Page;
    faqentries: Faqentry;
    partners: Partner;
    testimonials: Testimonial;
    websites: Website;
    locales: Locale;
    menus: Menu;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqentries: FaqentriesSelect<false> | FaqentriesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    websites: WebsitesSelect<false> | WebsitesSelect<true>;
    locales: LocalesSelect<false> | LocalesSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  path: string;
  slug: string;
  website: number | Website;
  locale: number | Locale;
  title: string;
  sections?: (Header | Hero | Content | Collection | Longread | Medias | FAQ | Partners | Testimonials)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    metatags?:
      | {
          metatags: {
            name: string;
            value: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "websites".
 */
export interface Website {
  id: number;
  name: string;
  url: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locales".
 */
export interface Locale {
  id: number;
  locale: string;
  name: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Header".
 */
export interface Header {
  title?: string | null;
  subtitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'header';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero".
 */
export interface Hero {
  title: string;
  subtitle?: string | null;
  image?: (number | null) | Media;
  imagePlacement: 'left' | 'right' | 'top' | 'bottom' | 'behind';
  CTA?: boolean | null;
  cta?: {
    title: string;
    icon?: 'default' | null;
    color: 'default' | 'primary' | 'secondary' | 'accent' | 'success' | 'error' | 'warning' | 'info' | 'neutral';
    variant: 'solid' | 'outline' | 'tint' | 'ghost';
    type?: ('page' | 'url' | 'url_top') | null;
    page?: (number | null) | Page;
    url?: string | null;
  };
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Content".
 */
export interface Content {
  title?: string | null;
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  imagePlacement: 'left' | 'right' | 'top' | 'bottom' | 'behind';
  CTA?: boolean | null;
  cta?: {
    title: string;
    icon?: 'default' | null;
    color: 'default' | 'primary' | 'secondary' | 'accent' | 'success' | 'error' | 'warning' | 'info' | 'neutral';
    variant: 'solid' | 'outline' | 'tint' | 'ghost';
    type?: ('page' | 'url' | 'url_top') | null;
    page?: (number | null) | Page;
    url?: string | null;
  };
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Collection".
 */
export interface Collection {
  kind: 'cards' | 'tabs' | 'grid' | 'flex' | 'list' | 'progress' | 'instructions';
  items: {
    brick?: {
      headline?: string | null;
      title?: string | null;
      subtitle?: string | null;
      icon?: 'default' | null;
      image?: (number | null) | Media;
      type?: ('page' | 'url' | 'url_top') | null;
      page?: (number | null) | Page;
      url?: string | null;
    };
    id?: string | null;
  }[];
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'collection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Longread".
 */
export interface Longread {
  items: {
    text: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'longread';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Medias".
 */
export interface Medias {
  items: {
    media_item?: {
      type?: ('photo' | 'video' | 'youtube' | 'vimeo') | null;
      youtube_id?: string | null;
      vimeo_id?: string | null;
      image?: (number | null) | Media;
      video?: (number | null) | Media;
    };
    id?: string | null;
  }[];
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'medias';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQ".
 */
export interface FAQ {
  items: (number | Faqentry)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqentries".
 */
export interface Faqentry {
  id: number;
  title: string;
  text: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Partners".
 */
export interface Partners {
  items: (number | Partner)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'partners';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  image: number | Media;
  description?: string | null;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Testimonials".
 */
export interface Testimonials {
  items: (number | Testimonial)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  company?: string | null;
  position?: string | null;
  image: number | Media;
  description: string;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  name: string;
  website: number | Website;
  locale: number | Locale;
  items: (
    | {
        title: string;
        icon?: 'default' | null;
        image?: (number | null) | Media;
        items: {
          menuitem: {
            title: string;
            icon?: 'default' | null;
            image?: (number | null) | Media;
            type?: ('page' | 'url' | 'url_top') | null;
            page?: (number | null) | Page;
            url?: string | null;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'menuholder';
      }
    | {
        title: string;
        icon?: 'default' | null;
        image?: (number | null) | Media;
        type?: ('page' | 'url' | 'url_top') | null;
        page?: (number | null) | Page;
        url?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menublock';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqentries';
        value: number | Faqentry;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'websites';
        value: number | Website;
      } | null)
    | ({
        relationTo: 'locales';
        value: number | Locale;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  path?: T;
  slug?: T;
  website?: T;
  locale?: T;
  title?: T;
  sections?:
    | T
    | {
        header?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              image?: T;
              imagePlacement?: T;
              CTA?: T;
              cta?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    color?: T;
                    variant?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                  };
              options?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              title?: T;
              subtitle?: T;
              text?: T;
              image?: T;
              imagePlacement?: T;
              CTA?: T;
              cta?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    color?: T;
                    variant?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                  };
              options?: T;
              id?: T;
              blockName?: T;
            };
        collection?:
          | T
          | {
              kind?: T;
              items?:
                | T
                | {
                    brick?:
                      | T
                      | {
                          headline?: T;
                          title?: T;
                          subtitle?: T;
                          icon?: T;
                          image?: T;
                          type?: T;
                          page?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              options?: T;
              id?: T;
              blockName?: T;
            };
        longread?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              options?: T;
              id?: T;
              blockName?: T;
            };
        medias?:
          | T
          | {
              items?:
                | T
                | {
                    media_item?:
                      | T
                      | {
                          type?: T;
                          youtube_id?: T;
                          vimeo_id?: T;
                          image?: T;
                          video?: T;
                        };
                    id?: T;
                  };
              options?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              items?: T;
              id?: T;
              blockName?: T;
            };
        partners?:
          | T
          | {
              items?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              items?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        metatags?:
          | T
          | {
              metatags?:
                | T
                | {
                    name?: T;
                    value?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqentries_select".
 */
export interface FaqentriesSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  description?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  position?: T;
  image?: T;
  description?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "websites_select".
 */
export interface WebsitesSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locales_select".
 */
export interface LocalesSelect<T extends boolean = true> {
  locale?: T;
  name?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  website?: T;
  locale?: T;
  items?:
    | T
    | {
        menuholder?:
          | T
          | {
              title?: T;
              icon?: T;
              image?: T;
              items?:
                | T
                | {
                    menuitem?:
                      | T
                      | {
                          title?: T;
                          icon?: T;
                          image?: T;
                          type?: T;
                          page?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        menublock?:
          | T
          | {
              title?: T;
              icon?: T;
              image?: T;
              type?: T;
              page?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}